//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace CityParkWS.ahuzot.parkinfo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CPSoap", Namespace="http://Target/AhuzatDataDist/CP/")]
    public partial class CP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCarParkDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCarParkStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCarParkDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCarParkStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CP() {
            this.Url = global::CityParkWS.Properties.Settings.Default.CityParkWS_ahuzot_parkinfo_CP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCarParkDetailsCompletedEventHandler GetCarParkDetailsCompleted;
        
        /// <remarks/>
        public event GetCarParkStatusCompletedEventHandler GetCarParkStatusCompleted;
        
        /// <remarks/>
        public event GetAllCarParkDetailsCompletedEventHandler GetAllCarParkDetailsCompleted;
        
        /// <remarks/>
        public event GetAllCarParkStatusCompletedEventHandler GetAllCarParkStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Target/AhuzatDataDist/CP/GetCarParkDetails", RequestNamespace="http://Target/AhuzatDataDist/CP/", ResponseNamespace="http://Target/AhuzatDataDist/CP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CarParkStaticDetails GetCarParkDetails(int fAhuzotCode, string fUserName, string fPassword, ref string tFault, string fWSPwd) {
            object[] results = this.Invoke("GetCarParkDetails", new object[] {
                        fAhuzotCode,
                        fUserName,
                        fPassword,
                        tFault,
                        fWSPwd});
            tFault = ((string)(results[1]));
            return ((CarParkStaticDetails)(results[0]));
        }
        
        /// <remarks/>
        public void GetCarParkDetailsAsync(int fAhuzotCode, string fUserName, string fPassword, string tFault, string fWSPwd) {
            this.GetCarParkDetailsAsync(fAhuzotCode, fUserName, fPassword, tFault, fWSPwd, null);
        }
        
        /// <remarks/>
        public void GetCarParkDetailsAsync(int fAhuzotCode, string fUserName, string fPassword, string tFault, string fWSPwd, object userState) {
            if ((this.GetCarParkDetailsOperationCompleted == null)) {
                this.GetCarParkDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCarParkDetailsOperationCompleted);
            }
            this.InvokeAsync("GetCarParkDetails", new object[] {
                        fAhuzotCode,
                        fUserName,
                        fPassword,
                        tFault,
                        fWSPwd}, this.GetCarParkDetailsOperationCompleted, userState);
        }
        
        private void OnGetCarParkDetailsOperationCompleted(object arg) {
            if ((this.GetCarParkDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCarParkDetailsCompleted(this, new GetCarParkDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Target/AhuzatDataDist/CP/GetCarParkStatus", RequestNamespace="http://Target/AhuzatDataDist/CP/", ResponseNamespace="http://Target/AhuzatDataDist/CP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CarParkDynamicDetails GetCarParkStatus(int fAhuzotCode, string fUserName, string fPassword, ref string tFault, string fWSPwd) {
            object[] results = this.Invoke("GetCarParkStatus", new object[] {
                        fAhuzotCode,
                        fUserName,
                        fPassword,
                        tFault,
                        fWSPwd});
            tFault = ((string)(results[1]));
            return ((CarParkDynamicDetails)(results[0]));
        }
        
        /// <remarks/>
        public void GetCarParkStatusAsync(int fAhuzotCode, string fUserName, string fPassword, string tFault, string fWSPwd) {
            this.GetCarParkStatusAsync(fAhuzotCode, fUserName, fPassword, tFault, fWSPwd, null);
        }
        
        /// <remarks/>
        public void GetCarParkStatusAsync(int fAhuzotCode, string fUserName, string fPassword, string tFault, string fWSPwd, object userState) {
            if ((this.GetCarParkStatusOperationCompleted == null)) {
                this.GetCarParkStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCarParkStatusOperationCompleted);
            }
            this.InvokeAsync("GetCarParkStatus", new object[] {
                        fAhuzotCode,
                        fUserName,
                        fPassword,
                        tFault,
                        fWSPwd}, this.GetCarParkStatusOperationCompleted, userState);
        }
        
        private void OnGetCarParkStatusOperationCompleted(object arg) {
            if ((this.GetCarParkStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCarParkStatusCompleted(this, new GetCarParkStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Target/AhuzatDataDist/CP/GetAllCarParkDetails", RequestNamespace="http://Target/AhuzatDataDist/CP/", ResponseNamespace="http://Target/AhuzatDataDist/CP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CarParkStaticDetails[] GetAllCarParkDetails(string fUserName, string fPassword, ref string tFault, string fWSPwd) {
            object[] results = this.Invoke("GetAllCarParkDetails", new object[] {
                        fUserName,
                        fPassword,
                        tFault,
                        fWSPwd});
            tFault = ((string)(results[1]));
            return ((CarParkStaticDetails[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCarParkDetailsAsync(string fUserName, string fPassword, string tFault, string fWSPwd) {
            this.GetAllCarParkDetailsAsync(fUserName, fPassword, tFault, fWSPwd, null);
        }
        
        /// <remarks/>
        public void GetAllCarParkDetailsAsync(string fUserName, string fPassword, string tFault, string fWSPwd, object userState) {
            if ((this.GetAllCarParkDetailsOperationCompleted == null)) {
                this.GetAllCarParkDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCarParkDetailsOperationCompleted);
            }
            this.InvokeAsync("GetAllCarParkDetails", new object[] {
                        fUserName,
                        fPassword,
                        tFault,
                        fWSPwd}, this.GetAllCarParkDetailsOperationCompleted, userState);
        }
        
        private void OnGetAllCarParkDetailsOperationCompleted(object arg) {
            if ((this.GetAllCarParkDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCarParkDetailsCompleted(this, new GetAllCarParkDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Target/AhuzatDataDist/CP/GetAllCarParkStatus", RequestNamespace="http://Target/AhuzatDataDist/CP/", ResponseNamespace="http://Target/AhuzatDataDist/CP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CarParkDynamicDetails[] GetAllCarParkStatus(string fUserName, string fPassword, ref string tFault, string fWSPwd) {
            object[] results = this.Invoke("GetAllCarParkStatus", new object[] {
                        fUserName,
                        fPassword,
                        tFault,
                        fWSPwd});
            tFault = ((string)(results[1]));
            return ((CarParkDynamicDetails[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCarParkStatusAsync(string fUserName, string fPassword, string tFault, string fWSPwd) {
            this.GetAllCarParkStatusAsync(fUserName, fPassword, tFault, fWSPwd, null);
        }
        
        /// <remarks/>
        public void GetAllCarParkStatusAsync(string fUserName, string fPassword, string tFault, string fWSPwd, object userState) {
            if ((this.GetAllCarParkStatusOperationCompleted == null)) {
                this.GetAllCarParkStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCarParkStatusOperationCompleted);
            }
            this.InvokeAsync("GetAllCarParkStatus", new object[] {
                        fUserName,
                        fPassword,
                        tFault,
                        fWSPwd}, this.GetAllCarParkStatusOperationCompleted, userState);
        }
        
        private void OnGetAllCarParkStatusOperationCompleted(object arg) {
            if ((this.GetAllCarParkStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCarParkStatusCompleted(this, new GetAllCarParkStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Target/AhuzatDataDist/CP/")]
    public partial class CarParkStaticDetails {
        
        private int ahuzotCodeField;
        
        private int controllerIDField;
        
        private string nameField;
        
        private string addressField;
        
        private decimal gPSLattitudeField;
        
        private decimal gPSLongitudeField;
        
        private string daytimeFeeField;
        
        private string daytimeFeeWindowField;
        
        private string nighttimeFeeField;
        
        private string nighttimeFeeWindowField;
        
        private string dailyFeeField;
        
        private string dailyFeeWindowField;
        
        private string monthFeeForDailySubscriberField;
        
        private string monthFeeForDailySubscriberWindowField;
        
        private string monthFeeForNightlySubscriberField;
        
        private string monthFeeForNightlySubscriberWindowField;
        
        private string feeCommentsField;
        
        private string openWindowField;
        
        private int maximumPublicOccupancyField;
        
        private int maximumSubscriberOccupancyField;
        
        private string extra01Field;
        
        private string extra02Field;
        
        private string extra03Field;
        
        private string extra04Field;
        
        private string extra05Field;
        
        /// <remarks/>
        public int AhuzotCode {
            get {
                return this.ahuzotCodeField;
            }
            set {
                this.ahuzotCodeField = value;
            }
        }
        
        /// <remarks/>
        public int ControllerID {
            get {
                return this.controllerIDField;
            }
            set {
                this.controllerIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public decimal GPSLattitude {
            get {
                return this.gPSLattitudeField;
            }
            set {
                this.gPSLattitudeField = value;
            }
        }
        
        /// <remarks/>
        public decimal GPSLongitude {
            get {
                return this.gPSLongitudeField;
            }
            set {
                this.gPSLongitudeField = value;
            }
        }
        
        /// <remarks/>
        public string DaytimeFee {
            get {
                return this.daytimeFeeField;
            }
            set {
                this.daytimeFeeField = value;
            }
        }
        
        /// <remarks/>
        public string DaytimeFeeWindow {
            get {
                return this.daytimeFeeWindowField;
            }
            set {
                this.daytimeFeeWindowField = value;
            }
        }
        
        /// <remarks/>
        public string NighttimeFee {
            get {
                return this.nighttimeFeeField;
            }
            set {
                this.nighttimeFeeField = value;
            }
        }
        
        /// <remarks/>
        public string NighttimeFeeWindow {
            get {
                return this.nighttimeFeeWindowField;
            }
            set {
                this.nighttimeFeeWindowField = value;
            }
        }
        
        /// <remarks/>
        public string DailyFee {
            get {
                return this.dailyFeeField;
            }
            set {
                this.dailyFeeField = value;
            }
        }
        
        /// <remarks/>
        public string DailyFeeWindow {
            get {
                return this.dailyFeeWindowField;
            }
            set {
                this.dailyFeeWindowField = value;
            }
        }
        
        /// <remarks/>
        public string MonthFeeForDailySubscriber {
            get {
                return this.monthFeeForDailySubscriberField;
            }
            set {
                this.monthFeeForDailySubscriberField = value;
            }
        }
        
        /// <remarks/>
        public string MonthFeeForDailySubscriberWindow {
            get {
                return this.monthFeeForDailySubscriberWindowField;
            }
            set {
                this.monthFeeForDailySubscriberWindowField = value;
            }
        }
        
        /// <remarks/>
        public string MonthFeeForNightlySubscriber {
            get {
                return this.monthFeeForNightlySubscriberField;
            }
            set {
                this.monthFeeForNightlySubscriberField = value;
            }
        }
        
        /// <remarks/>
        public string MonthFeeForNightlySubscriberWindow {
            get {
                return this.monthFeeForNightlySubscriberWindowField;
            }
            set {
                this.monthFeeForNightlySubscriberWindowField = value;
            }
        }
        
        /// <remarks/>
        public string FeeComments {
            get {
                return this.feeCommentsField;
            }
            set {
                this.feeCommentsField = value;
            }
        }
        
        /// <remarks/>
        public string OpenWindow {
            get {
                return this.openWindowField;
            }
            set {
                this.openWindowField = value;
            }
        }
        
        /// <remarks/>
        public int MaximumPublicOccupancy {
            get {
                return this.maximumPublicOccupancyField;
            }
            set {
                this.maximumPublicOccupancyField = value;
            }
        }
        
        /// <remarks/>
        public int MaximumSubscriberOccupancy {
            get {
                return this.maximumSubscriberOccupancyField;
            }
            set {
                this.maximumSubscriberOccupancyField = value;
            }
        }
        
        /// <remarks/>
        public string Extra01 {
            get {
                return this.extra01Field;
            }
            set {
                this.extra01Field = value;
            }
        }
        
        /// <remarks/>
        public string Extra02 {
            get {
                return this.extra02Field;
            }
            set {
                this.extra02Field = value;
            }
        }
        
        /// <remarks/>
        public string Extra03 {
            get {
                return this.extra03Field;
            }
            set {
                this.extra03Field = value;
            }
        }
        
        /// <remarks/>
        public string Extra04 {
            get {
                return this.extra04Field;
            }
            set {
                this.extra04Field = value;
            }
        }
        
        /// <remarks/>
        public string Extra05 {
            get {
                return this.extra05Field;
            }
            set {
                this.extra05Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Target/AhuzatDataDist/CP/")]
    public partial class CarParkDynamicDetails {
        
        private int ahuzotCodeField;
        
        private string nameField;
        
        private string informationToShowField;
        
        private System.DateTime lastUpdateFromDambachField;
        
        /// <remarks/>
        public int AhuzotCode {
            get {
                return this.ahuzotCodeField;
            }
            set {
                this.ahuzotCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string InformationToShow {
            get {
                return this.informationToShowField;
            }
            set {
                this.informationToShowField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastUpdateFromDambach {
            get {
                return this.lastUpdateFromDambachField;
            }
            set {
                this.lastUpdateFromDambachField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCarParkDetailsCompletedEventHandler(object sender, GetCarParkDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCarParkDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCarParkDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CarParkStaticDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CarParkStaticDetails)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string tFault {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCarParkStatusCompletedEventHandler(object sender, GetCarParkStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCarParkStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCarParkStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CarParkDynamicDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CarParkDynamicDetails)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string tFault {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllCarParkDetailsCompletedEventHandler(object sender, GetAllCarParkDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCarParkDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCarParkDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CarParkStaticDetails[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CarParkStaticDetails[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string tFault {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllCarParkStatusCompletedEventHandler(object sender, GetAllCarParkStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCarParkStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCarParkStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CarParkDynamicDetails[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CarParkDynamicDetails[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string tFault {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591